name: Crowdin Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Crowdin files
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          crowdin_branch_name: main
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          CROWDIN_PROJECT_ID: "784288"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
